const { faker } = require('@faker-js/faker');
const express = require("express");
const path = require("path");
let app = express();
const methodOverride = require("method-override");
const { v4: uuidv4 } = require('uuid');
let port = 3000;


app.use(methodOverride("_method"));
app.use(express.urlencoded({ extended: true }));
app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "/views"));
app.use(express.static(path.join(__dirname, "public")));

app.listen(port, (req, res) => {
  console.log("Server is listening at port 3000.");
})

/* Show total number of users */
app.get("/", (req, res) => {
  let q = `SELECT count(*) FROM boys_info`;
  try {
    connection.query(q, (error, result) => {
      if (error)
        throw error;
      else {
        let count = result[0]["count(*)"];
        console.log(count);
        res.render("user.ejs", { count });
      }
    })
  } catch (error) {
    console.log(error);
    res.send("Something is wrong!");
  }
});

/* Show all Users */
app.get("/user", (req, res) => {
  let q = `SELECT * FROM boys_info`;
  try {
    connection.query(q, (error, result) => {
      if (error)
        throw error;
      else {
        let users = result;
        console.log("I am present!");
        res.render("showuser.ejs", { users });
      }
    })
  } catch (error) {
    console.log(error);
    res.send("Something is wrong!");
  }
});

/* Edit your Post */
app.get("/user/:id/edit", (req, res) => {
  let { id } = req.params;
  let q = `SELECT * FROM boys_info WHERE id = "${id}"`;
  try {
    connection.query(q, (error, result) => {
      if (error)
        throw error;
      else {
        console.log("I am available!");
        console.log(result);
        res.render("Edituser.ejs", { result });
      }
    })
  } catch (error) {
    console.log(error);
    res.send("Something is wrong!");
  }
})

/* Update your Post */
app.patch("/user/:id", (req, res) => {
  let { id } = req.params;
  let { password, username } = req.body;
  let new_password = password, new_username = username;
  let q = `SELECT * FROM boys_info WHERE id = "${id}"`;
  try {
    connection.query(q, (error, select) => {
      if (error)
        throw error;
      else {
        try {
          if (new_password == select[0].password) {
            let new_query = `UPDATE boys_info SET username = "${new_username}" WHERE id = "${id}"`;
            connection.query(new_query, (error, result) => {
              if (error)
                throw error;
              else {
                console.log(result);
                res.redirect("/user");
              }
            })
          }
        } catch (error) {
          console.log(error);
          res.send("Error is happened!");
        }
      }
    })
  } catch (error) {
    console.log(error);
    res.send("Something is wrong!");
  }
})

/* DELETE User */
app.delete("/user/:id", (req, res) => {
  let { id } = req.params;
  console.log(id);
  let q = `DELETE FROM boys_info WHERE id = "${id}"`;
  try {
    connection.query(q, (error, result) => {
      if (error)
        throw error;
      else {
        res.redirect("/user");
        console.log("Your request is recived!");
      }
    })
  } catch (error) {
    console.log(error);
    console.log("something is wrong!");
  }
})

/* Add New User */
app.get("/user/add_new", (req, res) => {
  let id = uuidv4();
  res.render("Add_newUser.ejs", { id });
  console.log(id);
});

app.post("/user/:id/new", (req, res) => {
  let { id } = req.params;
  let { username, email, password } = req.body;
  let q = `INSERT INTO boys_info (id, username, email, password) VALUES ("${id}", "${username}", "${email}", "${password}")`;
  try {
    connection.query(q, (error, result) => {
      if (error)
        throw (error);
      else {
        res.redirect("/user");
      }
    })
  } catch (error) {
    console.log("Something is wrong!");
    console.log(error);
  }
})
// let createRandomUser = ()=> {
//   return [
//     faker.string.uuid(),
//     faker.internet.userName(),
//     faker.internet.email(),
//     faker.internet.password(),
//   ]
// }

// console.log(createRandomUser());

let mysql = require("mysql2");

let connection = mysql.createConnection({
  host: "localhost",
  user: "root",
  database: "school",
  password: "MySQL_table",
});

//Insert Multiple data into student table of the school database.
// let query = "INSERT INTO student (id, name, email, city) VALUES ?";
// let array_of_array = [
//   [1010, "khalid", "Skhalia@gamil.com", "latamber"],
//   [1006, "Ahmad", "Ahmadgamil.com", "Multan"],
//   [1007, "Wajid", "Wajid@gamil.com", "islamabad"],
//   [1008, "faisal", "faisal@gamil.com", "lahore"]
// ];

//Insert random data that generated by th faker.
/*
let query = "INSERT INTO boys_info (id, username, email, password) VALUES ?";
let array_of_array = [];
for(let i = 0; i<50; i++){
 array_of_array[i] = createRandomUser();
}

try{
  connection.query(query, [array_of_array] ,(err,res)=>{
  if(err) throw err;
  console.log("No error found!");
  console.log(res);
  })
}catch(err){
  console.log("Your error is: ",err);
}

connection.end();
*/
